#ifndef myoptions_h
#define myoptions_h

/* Generated by myoptions.h generator - v0.8.1 */
/* https://e2002.github.io/docs/myoptions-generator.html?r=72,1,2,3,8,11,36,41,43,49,50,53&i=1,2,3,4,15,16,17,22,23,24&v=5,14,-1,255,27,26,25,15,13,12 */
/* Put this file next to yoRadio.ino and restart Arduino IDE. */

/* !!! Attention !!! */
/* This configuration depends on some additional libraries. Please install them using the library manager: */
/* Adafruit GFX Library, Adafruit ST7735 and ST7789 Library, OneButton */

/* !!! Do not be alarmed, all right, the default values ​​are not included in this file !!! */

// Changes using app: flip screen

#define L10N_LANGUAGE     EN 
#define DSP_MODEL			DSP_ST7735
#define DTYPE INITR_BLACKTAB
#define TFT_ROTATE 2 
#define TFT_CS                 14
#define TFT_RST                -1       // connected to EN (reset) of ESP32
#define TFT_DC                 05
#define TFT_SCK                13    // SPI Clock (GPIO13)
#define TFT_MOSI               11    // SPI MOSI (GPIO11) 

#define I2S_DOUT               40
#define I2S_BCLK               41
#define I2S_LRC                42

#define BTN_LEFT			16
#define BTN_CENTER			06
#define BTN_RIGHT			17
#define SD_HSPI 0

#define PLAYER_FORCE_MONO true

#endif
